# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(319, 277)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.app_name = QtWidgets.QLabel(self.centralwidget)
        self.app_name.setGeometry(QtCore.QRect(8, 1, 141, 31))
        self.app_name.setObjectName("app_name")
        self.score = QtWidgets.QLabel(self.centralwidget)
        self.score.setGeometry(QtCore.QRect(8, 46, 301, 31))
        self.score.setStyleSheet("color: rgb(0, 0, 0);\n"
"border-width: 2px;\n"
"border-style: solid;\n"
"border-color: black;\n"
"")
        self.score.setObjectName("score")
        self.button_1 = QtWidgets.QPushButton(self.centralwidget)
        self.button_1.setGeometry(QtCore.QRect(-1, 179, 75, 23))
        self.button_1.setObjectName("button_1")
        self.button_equal = QtWidgets.QPushButton(self.centralwidget)
        self.button_equal.setGeometry(QtCore.QRect(-1, 208, 75, 23))
        self.button_equal.setObjectName("button_equal")
        self.button_div = QtWidgets.QPushButton(self.centralwidget)
        self.button_div.setGeometry(QtCore.QRect(161, 92, 75, 23))
        self.button_div.setObjectName("button_div")
        self.button_4 = QtWidgets.QPushButton(self.centralwidget)
        self.button_4.setGeometry(QtCore.QRect(-1, 150, 75, 23))
        self.button_4.setObjectName("button_4")
        self.button_pcnt = QtWidgets.QPushButton(self.centralwidget)
        self.button_pcnt.setGeometry(QtCore.QRect(-1, 92, 75, 23))
        self.button_pcnt.setObjectName("button_pcnt")
        self.button_plus = QtWidgets.QPushButton(self.centralwidget)
        self.button_plus.setGeometry(QtCore.QRect(242, 150, 75, 23))
        self.button_plus.setObjectName("button_plus")
        self.button_sqrt = QtWidgets.QPushButton(self.centralwidget)
        self.button_sqrt.setGeometry(QtCore.QRect(80, 92, 75, 23))
        self.button_sqrt.setObjectName("button_sqrt")
        self.button_9 = QtWidgets.QPushButton(self.centralwidget)
        self.button_9.setGeometry(QtCore.QRect(161, 121, 75, 23))
        self.button_9.setObjectName("button_9")
        self.button_6 = QtWidgets.QPushButton(self.centralwidget)
        self.button_6.setGeometry(QtCore.QRect(161, 150, 75, 23))
        self.button_6.setAutoDefault(False)
        self.button_6.setObjectName("button_6")
        self.button_0 = QtWidgets.QPushButton(self.centralwidget)
        self.button_0.setGeometry(QtCore.QRect(80, 208, 75, 23))
        self.button_0.setObjectName("button_0")
        self.button_clear = QtWidgets.QPushButton(self.centralwidget)
        self.button_clear.setEnabled(True)
        self.button_clear.setGeometry(QtCore.QRect(242, 179, 75, 52))
        self.button_clear.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.button_clear.setObjectName("button_clear")
        self.button_2 = QtWidgets.QPushButton(self.centralwidget)
        self.button_2.setGeometry(QtCore.QRect(80, 179, 75, 23))
        self.button_2.setObjectName("button_2")
        self.button_7 = QtWidgets.QPushButton(self.centralwidget)
        self.button_7.setGeometry(QtCore.QRect(-1, 121, 75, 23))
        self.button_7.setObjectName("button_7")
        self.button_3 = QtWidgets.QPushButton(self.centralwidget)
        self.button_3.setGeometry(QtCore.QRect(161, 179, 75, 23))
        self.button_3.setObjectName("button_3")
        self.button_dot = QtWidgets.QPushButton(self.centralwidget)
        self.button_dot.setGeometry(QtCore.QRect(161, 208, 75, 23))
        self.button_dot.setObjectName("button_dot")
        self.button_prod = QtWidgets.QPushButton(self.centralwidget)
        self.button_prod.setGeometry(QtCore.QRect(242, 92, 75, 23))
        self.button_prod.setObjectName("button_prod")
        self.button_minus = QtWidgets.QPushButton(self.centralwidget)
        self.button_minus.setGeometry(QtCore.QRect(242, 121, 75, 23))
        self.button_minus.setObjectName("button_minus")
        self.button_8 = QtWidgets.QPushButton(self.centralwidget)
        self.button_8.setGeometry(QtCore.QRect(80, 121, 75, 23))
        self.button_8.setObjectName("button_8")
        self.button_5 = QtWidgets.QPushButton(self.centralwidget)
        self.button_5.setGeometry(QtCore.QRect(80, 150, 75, 23))
        self.button_5.setObjectName("button_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 319, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.app_name.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600;\">Calculator</span></p></body></html>"))
        self.score.setText(_translate("MainWindow", "<html>\n"
"<head>\n"
"    <style>\n"
"    p {\n"
"    border: 1px solid black;\n"
"    padding: 10px;\n"
"    }\n"
"    </style>\n"
"</head>\n"
"<body>\n"
"    <p align=\"right\">\n"
"    <span style=\" font-size:20pt;\">0</span>\n"
"    </p>\n"
"</body>\n"
"</html>"))
        self.button_1.setText(_translate("MainWindow", "1"))
        self.button_equal.setText(_translate("MainWindow", "="))
        self.button_div.setText(_translate("MainWindow", "/"))
        self.button_4.setText(_translate("MainWindow", "4"))
        self.button_pcnt.setText(_translate("MainWindow", "%"))
        self.button_plus.setText(_translate("MainWindow", "+"))
        self.button_sqrt.setText(_translate("MainWindow", "√"))
        self.button_9.setText(_translate("MainWindow", "9"))
        self.button_6.setText(_translate("MainWindow", "6"))
        self.button_0.setText(_translate("MainWindow", "0"))
        self.button_clear.setText(_translate("MainWindow", "C"))
        self.button_2.setText(_translate("MainWindow", "2"))
        self.button_7.setText(_translate("MainWindow", "7"))
        self.button_3.setText(_translate("MainWindow", "3"))
        self.button_dot.setText(_translate("MainWindow", "."))
        self.button_prod.setText(_translate("MainWindow", "*"))
        self.button_minus.setText(_translate("MainWindow", "-"))
        self.button_8.setText(_translate("MainWindow", "8"))
        self.button_5.setText(_translate("MainWindow", "5"))
